### ISSUE TITLE
북마크 버튼 클릭 시 place bookmark count 업데이트 안됨

### ISSUE THREAD

**Issue by minjj0905** [likelion-kookmin/daedong-food-map#215]

**Comment by minjj0905** [comment]
![image](https://user-images.githubusercontent.com/55120738/129084521-ceb2fd48-db9d-4e11-92c1-1cb10ea41405.png)
![image](https://user-images.githubusercontent.com/55120738/129084540-497e7669-a6e1-41e0-964e-b504f0f96232.png)

**Comment by shinkeonkim** [comment]
현재 signal 구조를 바꿔야 함.

**Comment by shinkeonkim** [comment]
기능은 정상작동함
