### ISSUE TITLE
로고 디자인

### ISSUE THREAD

**Issue by shinkeonkim** [likelion-kookmin/daedong-food-map#5]

**Comment by minjj0905** [comment]
![Logo](https://user-images.githubusercontent.com/55120738/128105582-93836ced-6320-40c5-86bb-7a7af49f5fa9.png)
![LogoTitle](https://user-images.githubusercontent.com/55120738/128105587-90f81975-0d64-4d8a-96b6-25685a797102.png)
![LogoUnderTitle](https://user-images.githubusercontent.com/55120738/128105588-9898bf00-5614-4ea0-a34c-a126a7c13801.png)

로고 3종이용

**Comment by minjj0905** [comment]
![LogoTitle](https://user-images.githubusercontent.com/55120738/128105600-d4b482e7-6ca4-4137-8b93-a7603cd91d50.png)
