### ISSUE TITLE
frontend app initial settings

### ISSUE THREAD

**Issue by shinkeonkim** [likelion-kookmin/daedong-food-map#7]
2021.08.02 까지

**Comment by minjj0905** [comment]
![Logo](https://user-images.githubusercontent.com/55120738/127818354-74cd7e88-8aaa-4968-ac6d-1a367bb0e9b2.png)
![LogoTitle](https://user-images.githubusercontent.com/55120738/127818356-372bc612-6fd5-42c9-b8ee-bc723d61253b.png)
![LogoUnderTitle](https://user-images.githubusercontent.com/55120738/127818358-2c80af12-368e-4437-8ae4-2069bf2319dc.png)

로고 세개 입니당.
디자인 의견 있으신분 자유롭게 주셔용.
