### ISSUE TITLE
Reports#new form 디자인 및 개발

### ISSUE THREAD

**Issue by shinkeonkim** [likelion-kookmin/daedong-food-map#77]

**Comment by minjj0905** [comment]
![image](https://user-images.githubusercontent.com/55120738/128466368-20c6a496-f879-4950-9311-2dc45e042a0a.png)
![image](https://user-images.githubusercontent.com/55120738/128466383-fc0aa772-c4b4-4bf2-8b63-7380ba6df96d.png)
![image](https://user-images.githubusercontent.com/55120738/128466394-3e742016-71cc-4a38-8e84-986b3dcee32e.png)

자세한 디자인은 XD에서
